### ISSUE TITLE
how to test my trained mode?

### ISSUE THREAD

**Issue by fan8502** [yashbonde/nqg#1]
Hi,
Firstly thanks for the repo which is really helpful.

If you can give me instructions on how to test my trained model (i.e, taking a paragraph(source), pos, ner) and generate a question as output it would be very helpful.

Thanks a lot!

**Comment by yashbonde** [comment]
Hey bud, thanks for your interest in this. Unfortunately is discontinued work on this over two years ago as company's priorities changes, and repo is incomplete. However thank you for bringing light on this, I might pick this up over a weekend and try to complete it. I still remember though that using the `tf.nn.dynamic_rnn()` was slightly tricky and was one of the reasons we did not continue working on this.
Just throwing ideas, but why don't you try using Transformer Network as a slight modification and I have been working on those for over a year now. Again, thank you for reminding me of this project, will complete it someday.
